# Generated by Django 2.2.4 on 2020-12-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0005_auto_20201229_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
