# Generated by Django 2.2.4 on 2020-12-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theApp', '0006_auto_20201229_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
